export const  FETCH_URL_ITEMS = "http://localhost:3001/items";



export const  GET_CHECKING_REQUEST = "GET_CHECKING_REQUEST";
export const  GET_CHECKING_SUCSESS = "GET_CHECKING_SUCSESS";
export const  GET_CHECKING_RFAILURE = "GET_CHECKING_RFAILURE";

export const  POST_ITEM_EXCEL_REQUEST = "POST_ITEM_EXCEL_REQUEST";
export const  POST_ITEM_EXCEL_SUCSESS = "POST_ITEM_EXCEL_SUCSESS";
export const  POST_ITEM_EXCEL_RFAILURE = "POST_ITEM_EXCEL_RFAILURE";

export const  CHANGE_PRINT_STATUS_REQUEST = "CHANGE_PRINT_STATUS_REQUEST";
export const  CHANGE_PRINT_STATUS_SUCSESS = "CHANGE_PRINT_STATUS_SUCSESS";
export const  CHANGE_PRINT_STATUS_RFAILURE = "CHANGE_PRINT_STATUS_RFAILURE";