export const  FETCH_URL_ITEMS = "http://localhost:3001/items";
export const   CLOUDINARY_URL_CDN = "https://res.cloudinary.com/hieudz/image/upload/v1566581774/demo%20tool/";

export const  STATE_POST_TO_DEFAULT = "STATE_POST_TO_DEFAULT";

export const  GET_CHECKING_REQUEST = "GET_CHECKING_REQUEST";
export const  GET_CHECKING_SUCSESS = "GET_CHECKING_SUCSESS";
export const  GET_CHECKING_RFAILURE = "GET_CHECKING_RFAILURE";

export const  POST_ITEM_EXCEL_REQUEST = "POST_ITEM_EXCEL_REQUEST";
export const  POST_ITEM_EXCEL_SUCSESS = "POST_ITEM_EXCEL_SUCSESS";
export const  POST_ITEM_EXCEL_RFAILURE = "POST_ITEM_EXCEL_RFAILURE";

export const  PATCH_ITEM_EXCEL_FAIL_REQUEST = "PATCH_ITEM_EXCEL_FAIL_REQUEST";
export const  PATCH_ITEM_EXCEL_FAIL_SUCSESS = "PATCH_ITEM_EXCEL_FAIL_SUCSESS";
export const  PATCH_ITEM_EXCEL_FAIL_RFAILURE = "PATCH_ITEM_EXCEL_FAIL_RFAILURE";


export const  CHANGE_PRINT_STATUS_REQUEST = "CHANGE_PRINT_STATUS_REQUEST";
export const  CHANGE_PRINT_STATUS_SUCSESS = "CHANGE_PRINT_STATUS_SUCSESS";
export const  CHANGE_PRINT_STATUS_RFAILURE = "CHANGE_PRINT_STATUS_RFAILURE";

export const  PATCH_ITEM_CHECKING_PROPERTIES_REQUEST = "PATCH_ITEM_CHECKING_PROPERTIES_REQUEST";
export const  PATCH_ITEM_CHECKING_PROPERTIES_SUCSESS = "PATCH_ITEM_CHECKING_PROPERTIES_SUCSESS";
export const  PATCH_ITEM_CHECKING_PROPERTIES_RFAILURE = "PATCH_ITEM_CHECKING_PROPERTIES_RFAILURE";

export const  DELETE_ITEM_CHECKING_REQUEST = "DELETE_ITEM_CHECKING_REQUEST";
export const  DELETE_ITEM_CHECKING_SUCSESS = "DELETE_ITEM_CHECKING_SUCSESS";
export const  DELETE_ITEM_CHECKING_RFAILURE = "DELETE_ITEM_CHECKING_RFAILURE";

export const  ITEMS_PRINT_FALSE_REQUEST = "ITEMS_PRINT_FALSE_REQUEST";
export const  ITEMS_PRINT_FALSE_SUCSESS = "ITEMS_PRINT_FALSE_SUCSESS";
export const  ITEMS_PRINT_FALSE_RFAILURE = "ITEMS_PRINT_FALSE_RFAILURE";

export const  GET_LIST_BY_ID_REQUEST = "GET_LIST_BY_ID_REQUEST";
export const  GET_LIST_BY_ID_SUCSESS = "GET_LIST_BY_ID_SUCSESS";
export const  GET_LIST_RFAILURE = "GET_LIST_RFAILURE";

export const  GET_LIST_BY_CUSTOM_REQUEST = "GET_LIST_BY_CUSTOM_REQUEST";
export const  GET_LIST_BY_CUSTOM_SUCSESS = "GET_LIST_BY_CUSTOM_SUCSESS";










